export const localeText = {
  zh: {
    nav: {
      orientation: '导读',
      whitepaper: '白皮书',
      architecture: '架构',
      algorithms: '算法',
      academy: '学院',
      performance: '性能',
      reference: '参考',
      research: '研究',
    },
    sidebar: {
      orientationHub: '导读',
      whitepaperHub: '白皮书',
      architectureHub: '架构',
      algorithmsHub: '算法与流程',
      academyHub: '学院',
      performanceHub: '性能证据',
      referenceHub: '参考',
      researchHub: '研究',
      narrativeContext: '叙事上下文',
      systemDesign: '系统设计',
      operatorRoutes: '操作路径',
      evidenceTrail: '证据链',
      whyFastqtools: '为什么选择 FastQTools',
      architecture: '架构',
      algorithms: '算法',
      knowledgeMap: '知识地图',
      workflows: '工作流',
      performance: '性能',
      benchmarkReport: 'Benchmark 报告',
      guide: '指南',
      guideOverview: '指南概览',
      gettingStarted: '快速开始',
      cliReference: 'CLI 参考',
      configuration: '配置',
      deployment: '部署',
      api: 'API 参考',
      apiOverview: 'API 概览',
      ioModule: 'IO 模块',
      processing: '处理模块',
      statistics: '统计模块',
      core: '核心模块',
      developer: '开发者指南',
      devOverview: '概览',
      devArchitecture: '架构设计',
      design: '核心设计',
      build: '构建指南',
      testing: '测试策略',
      codingStandards: '编码规范',
      localTooling: '本地工具',
      qualityTools: '代码质量',
      gitWorkflow: 'Git 工作流',
      devcontainer: 'DevContainer',
      benchmarkGuide: 'Benchmark 指南',
      referenceOverview: '参考概览',
      resourcesOverview: '资源导航',
      contributing: '参与贡献',
      releaseNotes: '发布说明',
      changelog: '变更记录',
      agents: 'Agent 文档',
      domain: '领域模型',
      issueTracker: 'Issue Tracker',
      triageLabels: '分类标签',
      archive: '归档',
      archiveOverview: '归档概览',
      migrationNotice: '迁移通知',
    },
    editLinkText: '在 GitHub 上编辑此页',
    footerCopyright: '基于 VitePress 构建',
  },
  en: {
    nav: {
      orientation: 'Orientation',
      whitepaper: 'Whitepaper',
      architecture: 'Architecture',
      algorithms: 'Algorithms',
      academy: 'Academy',
      performance: 'Performance',
      reference: 'Reference',
      research: 'Research',
    },
    sidebar: {
      orientationHub: 'Orientation',
      whitepaperHub: 'Whitepaper',
      architectureHub: 'Architecture',
      algorithmsHub: 'Algorithms and workflows',
      academyHub: 'Academy',
      performanceHub: 'Performance evidence',
      referenceHub: 'Reference',
      researchHub: 'Research',
      narrativeContext: 'Narrative context',
      systemDesign: 'System design',
      operatorRoutes: 'Operator paths',
      evidenceTrail: 'Evidence trail',
      whyFastqtools: 'Why FastQTools',
      architecture: 'Architecture',
      algorithms: 'Algorithms',
      knowledgeMap: 'Knowledge Map',
      workflows: 'Workflows',
      performance: 'Performance',
      benchmarkReport: 'Benchmark Report',
      guide: 'Guide',
      guideOverview: 'Guide Overview',
      gettingStarted: 'Getting Started',
      cliReference: 'CLI Reference',
      configuration: 'Configuration',
      deployment: 'Deployment',
      api: 'API Reference',
      apiOverview: 'API Overview',
      ioModule: 'IO Module',
      processing: 'Processing',
      statistics: 'Statistics',
      core: 'Core',
      developer: 'Developer Guide',
      devOverview: 'Overview',
      devArchitecture: 'Architecture',
      design: 'Design',
      build: 'Build',
      testing: 'Testing',
      codingStandards: 'Coding Standards',
      localTooling: 'Local Tooling',
      qualityTools: 'Quality Tools',
      gitWorkflow: 'Git Workflow',
      devcontainer: 'DevContainer',
      benchmarkGuide: 'Benchmark Guide',
      referenceOverview: 'Reference Overview',
      resourcesOverview: 'Resources Overview',
      contributing: 'Contributing',
      releaseNotes: 'Release Notes',
      changelog: 'Changelog',
      agents: 'Agent Docs',
      domain: 'Domain',
      issueTracker: 'Issue Tracker',
      triageLabels: 'Triage Labels',
      archive: 'Archive',
      archiveOverview: 'Overview',
      migrationNotice: 'Migration Notice',
    },
    editLinkText: 'Edit this page on GitHub',
    footerCopyright: 'Built with VitePress',
  },
} as const

export type LocaleKey = keyof typeof localeText
export type SidebarTextKey = keyof typeof localeText.en.sidebar

export const themeFoundation = {
  topLevelConcepts: ['whitepaper', 'architecture', 'algorithms', 'performance', 'referenceNav', 'researchNav'],
  sections: {
    whitepaper: {
      path: 'whitepaper/',
      aliases: ['orientation/', 'why-fastqtools/'],
      summary: {
        zh: '面向采用判断的主叙事入口。',
        en: 'Narrative entry point for adoption decisions.',
      },
    },
    architecture: {
      path: 'architecture/',
      aliases: ['knowledge-map/'],
      summary: {
        zh: '聚焦系统分层、执行模型与设计权衡。',
        en: 'System layers, execution model, and design trade-offs.',
      },
    },
    algorithms: {
      path: 'academy/',
      aliases: ['workflows/'],
      summary: {
        zh: '面向流程、算法与执行路径的学习入口。',
        en: 'Workflow and algorithm-oriented learning entry.',
      },
    },
    performance: {
      path: 'performance/',
      aliases: ['performance/benchmark-report'],
      summary: {
        zh: '维护中的 benchmark 证据与解释边界。',
        en: 'Maintained benchmark evidence and interpretation bounds.',
      },
    },
    referenceNav: {
      path: 'reference/',
      aliases: ['guide/', 'api/', 'dev/', 'release-notes/'],
      summary: {
        zh: 'CLI、API 与开发实现资料。',
        en: 'CLI, API, and developer implementation material.',
      },
    },
    researchNav: {
      path: 'research/',
      aliases: ['resources/', 'contributing/', 'agents/', 'archive/'],
      summary: {
        zh: '参考文献、协作上下文与研究补充。',
        en: 'References, collaboration context, and research adjuncts.',
      },
    },
  },
} as const

export type ThemeConceptId = keyof typeof themeFoundation.sections
